#!/bin/sh

if test ! $(which brew)
then
  echo "  x You should probably install Homebrew first: brew.sh"
  exit
else
  echo "  + Homebrew found."
fi

brew install git grc coreutils ag zsh vim hub chruby ruby-install
